import './globals.css'
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Try New Instance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
      {children}
      <Toaster />
	  </body>
    </html>
  )
}
